### ISSUE TITLE
404 css not loading

### ISSUE THREAD

**Issue by benbate** [benbate/benbate.github.io#9]

**Comment by YanniD** [comment]
I will check it out.

**Comment by benbate** [comment]
Thanks for the help @YanniD! That CSS seems to load. It's the 404 page CSS that won't load such as https://benbate.com/fdsfsd - any ideas why that might be?

**Comment by YanniD** [comment]
Woops accidently deleted my comment somehow , What i wrote earlier : 
You use `<link href="css/main.css" rel="stylesheet" media="all">` , this works but uses your css file and not the csss scss one. 

I will go check it out now for the 404 error, one sec :)

**Comment by YanniD** [comment]
I see . The thing that you mean if someone would go to a diffrent url they see that 404 page. For that you have to use some routing. You could use php for this or other languages but i would recommend php for now.  Here is a link that shows your problem and solves it : https://stackoverflow.com/questions/32912639/correct-way-to-display-404-page-in-php

**Comment by bultinckquentin** [comment]
![afbeelding](https://user-images.githubusercontent.com/17977577/34455681-77a62c82-ed84-11e7-83e5-2c95d092eb25.png)

Is your _404.css file empty?

**Comment by benbate** [comment]
@YanniD taking a look!

@bultinckquentin here's the CSS file https://github.com/benbate/benbate.github.io/blob/master/css/pages/_404.css

**Comment by YanniD** [comment]
Oh i see you have a live website already and it redirects to the right page. Forget then what i said earlier. I think the problem might be because that css file is starting with a '_' , Maybe try to name it 404.scss? It should have been linked correctly so its odd.

**Comment by benbate** [comment]
That's fixed it! Thanks a lot for your help @YanniD @bultinckquentin

**Comment by YanniD** [comment]
You are very welcome !
